// Trace the Omarchy mark with a head and fading tail, then loop the path.
// Generated by scripts/generate-mark.py: mark.png stores path distance in R,
// bevel normal XY in GB, and coverage in alpha. Geometry stays fixed.
#version 440

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;
    // How far along the path the tip has reached, in the same 0..1 the R
    // channel is normalised to. Runs a little past 1 to reach the path's end.
    float reveal;
    // Softness of the tip itself.
    float feather;
    // How far back from the tip the stroke is still hot.
    float head;
    // The drawing tip's position, continuing forward as the runner once drawn.
    float phase;
    // How far the runner's tail reaches back along the path.
    float pulse;
    // One screen pixel in texture coordinates, for the contact edge.
    vec2 pixel;
    // Sky light direction in baked-normal space: negative X left, Y above.
    vec2 key;
    vec4 tint;
    vec4 keyColor;
    float keyStrength;
};

layout(binding = 1) uniform sampler2D source;

float trail(float along) {
    float drawn = 1.0 - smoothstep(reveal - feather, reveal, along);
    float behind = phase - along;
    if (phase >= 1.0) behind = fract(behind);
    float tail = mix(head, pulse, smoothstep(0.80, 1.0, reveal));
    return (1.0 - smoothstep(feather, tail, behind)) * drawn;
}

float coverage(vec2 uv) {
    vec4 stroke = texture(source, uv);
    return stroke.a * trail(stroke.r);
}

void main() {
    vec4 s = texture(source, qt_TexCoord0);
    // Distance along the maze. The generator spreads this a few pixels past
    // the strokes, so linear filtering at a stroke's edge cannot mix in the
    // zero outside it and read as drawn before the tip ever arrived.
    float ink = s.a;

    // Only the head and fading tail remain; the completed path clears behind.
    float hot = trail(s.r);

    // Qt uploads premultiplied textures: recover the baked normal before
    // decoding it, so antialiased edges keep the same surface direction.
    vec2 normalXY = s.gb / max(ink, 0.001) * 2.0 - 1.0;
    vec3 normal = normalize(vec3(normalXY, sqrt(max(0.001, 1.0 - dot(normalXY, normalXY)))));
    vec3 view = vec3(0.0, 0.0, 1.0);
    // A grazing key separates the lit shoulder from the shaded underside.
    // Keep a coloured body under the highlight so the far side stays visible.
    // Follow the visible sun or moon. Z preserves frontal light at handover.
    vec3 lightDir = normalize(vec3(key, 0.45));
    float diffuse = max(dot(normal, lightDir), 0.0);
    float satin = pow(max(dot(normal, normalize(lightDir + view)), 0.0), 14.0);
    // Leave room for the coloured highlight instead of clipping it to white.
    vec3 face = tint.rgb * (0.50 + 0.35 * diffuse * keyStrength * mix(vec3(1.0), keyColor.rgb, 0.60));
    face += keyColor.rgb * satin * 0.55 * keyStrength;

    // The travelling light brings out the curved face locally. A broad
    // reflection gives satin a soft lustre instead of a sharp chrome glint.
    vec3 runner = normalize(vec3(0.25, 0.15, 1.0));
    float reflection = pow(max(dot(normal, normalize(runner + view)), 0.0), 10.0);
    face += hot * (tint.rgb * diffuse * 0.08 + vec3(0.28) * reflection);
    face = clamp(face, 0.0, 1.0);

    // Keep just a faint contact edge. The layer adds the diffuse shadow.
    float side = coverage(qt_TexCoord0 - pixel);
    // Fade coverage as well as lighting, including the contact edge below.
    float a = ink * hot;
    float sideAlpha = side * 0.25 * (1.0 - a);
    // Qt Quick composites premultiplied.
    fragColor = vec4(face * a + tint.rgb * 0.16 * sideAlpha,
                     a + sideAlpha) * qt_Opacity;
}
